Task 05 bon appetit 02 penetration test | adds feature for #9 (#45)
* add load test to pipeline

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -35,7 +35,7 @@ jobs:
     - name: Run Linting Script
       run: chmod +x ci/lint.sh && ci/lint.sh
 
-  Build:
+  build:
     runs-on: ubuntu-latest
     needs: [init]
     steps:
@@ -56,7 +56,7 @@ jobs:
 
   test:
     runs-on: ubuntu-latest
-    needs: [Build, lint]
+    needs: [build, lint]
     steps:
       - name: Download code
         uses: actions/download-artifact@v3
@@ -89,9 +89,42 @@ jobs:
         run: |
           docker-compose down
 
+  load-test:
+    needs: [test]
+    runs-on: ubuntu-latest
+    steps:
+      - name: Download code
+        uses: actions/download-artifact@v3
+        with:
+          name: code
+          path: .
+      - name: Pull repo docker images
+        run: chmod +x ci/pull-docker.sh && ci/pull-docker.sh
+      - name: Pull siege docker image
+        run: docker pull rufus/siege-engine:latest
+      - name: Run Docker Compose
+        run: |
+          docker-compose up -d
+      - name: Run Siege
+        id: siege_run # Assigning an ID for this step to access its outputs
+        run: |
+          docker run --network host rufus/siege-engine siege -c 10 -t 1M http://localhost:8080 || echo "Siege-failed" > siege_status.txt
+      - name: Check Siege Status
+        run: |
+          if [[ -f "siege_status.txt" && $(cat siege_status.txt) == "Siege-failed" ]]; then
+            echo "Siege encountered a failure!"
+            exit 1
+          fi
+      - name: Shut down Docker Compose
+        run: |
+          docker-compose down
+
+
+
+
   deploy:
     runs-on: ubuntu-latest
-    needs: [test]
+    needs: [availability-test, load-test]
     steps:
       - name: Download code
         uses: actions/download-artifact@v3
